packages:
  - codex-cli
  - codex-rs/responses-api-proxy/npm
  - sdk/typescript
  - shell-tool-mcp

blockExoticSubdeps: true

ignoredBuiltDependencies:
  - esbuild
  - unrs-resolver

minimumReleaseAge: 10080
